apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          command:
            - redis-server
            - /redis-config/redis.conf
          volumeMounts:
            - name: redis-config
              mountPath: /redis-config
            - name: redis-pvc
              mountPath: /data
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
