apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: {{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}
          ports:
            - containerPort: {{ (index .Values.payment.ports 0).port }}