apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: {{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}
                    env:
            - name: KAKAO_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: kakao.app_key
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: database.password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: database.url
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: database.port
            - name: DATABASE_USER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-app-secrets
                  key: database.dbName
          ports:
            - containerPort: {{ (index .Values.payment.ports 0).port }}