apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: {{ (index .Values.payment.ports 0).port }}
      targetPort: {{ (index .Values.payment.ports 0).targetPort }}
  type: ClusterIP