apiVersion: v1
kind: Secret
metadata:
  name: concert-app-secrets
  namespace: concert-ns
type: Opaque
data:
  database.username: 
  database.password: 
  database.port: 
  database.url: 
  database.dbName: 
  redis.host: 
  redis.port: 
