apiVersion: v1
kind: Secret
metadata:
  name: user-app-secrets
  namespace: user-ns
type: Opaque
data:
  kakao.client_id: 
  kakao.secret: 
  database.username: 
  database.password: 
  database.port: 
  database.url: 
  database.dbName: 
  redis.host: 
  redis.port: 