replicaCount: 5

image:
  repository: wlwlsus/back-gateway
  pullPolicy: IfNotPresent
  tag: 11

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.allback.site
      paths:
        - /
