replicaCount: 3

image:
  repository: wlwlsus/back-gateway
  pullPolicy: IfNotPresent
  tag: 4

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gateway.allback.site
      paths:
        - /
  tls: []

resources: {}
