apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: {{ .Values.user.replicas }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: {{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}
          ports:
            - containerPort: {{ (index .Values.user.ports 0).port }}