apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user-deployment
  namespace: mysql-user-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-user-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-concert-deployment
  namespace: mysql-concert-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-concert
  template:
    metadata:
      labels:
        app: mysql-concert
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: concert-db-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-concert-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-payment-deployment
  namespace: mysql-payment-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payment
  template:
    metadata:
      labels:
        app: mysql-payment
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-payment-pvc
