apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-app-secrets
                  key: redis.host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-app-secrets
                  key: redis.port
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP