apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: {{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}
          ports:
            - containerPort: {{ (index .Values.admin.ports 0).port }}