apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-deployment
spec:
  replicas: {{ .Values.concert.replicas }}
  selector:
    matchLabels:
      app: concert
  template:
    metadata:
      labels:
        app: concert
    spec:
      containers:
        - name: concert
          image: {{ .Values.concert.image.repository }}:{{ .Values.concert.image.tag }}
          ports:
            - containerPort: {{ (index .Values.concert.ports 0).port }}