apiVersion: v1
kind: Service
metadata:
  name: concert-service
spec:
  selector:
    app: concert
  ports:
    - protocol: TCP
      port: {{ (index .Values.concert.ports 0).port }}
      targetPort: {{ (index .Values.concert.ports 0).targetPort }}
  type: ClusterIP