apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: {{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}
          ports:
            - containerPort: {{ (index .Values.front.ports 0).port }}