apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
