apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
  - protocol: TCP
    port: {{ (index .Values.front.ports 0).port }}
    targetPort: {{ (index .Values.front.ports 0).targetPort }}
  type: LoadBalancer
  
