apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: {{ .Values.eureka.replicas }}
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: your-eureka-image:latest
          ports:
            - containerPort: {{ (index .Values.eureka.ports 0).port }}
