apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: {{.Values.eureka.ports[0].port}}
      targetPort: {{.Values.eureka.ports[0].targetPort}}
