apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: {{ (index .Values.eureka.ports 0).port }}
      targetPort: {{ (index .Values.eureka.ports 0).targetPort }}
  type: LoadBalancer